# Generated by Django 5.1.15 on 2026-02-09 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='caseactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='casefollowup',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='casenote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='casefollowup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casefollowup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='casenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='caseactionlog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('followup_added', 'Follow-up Added'), ('followup_completed', 'Follow-up Completed'), ('converted_from_prospect', 'Converted from Prospect')], max_length=64),
        ),
        migrations.AlterField(
            model_name='caseactionlog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
