# Generated by Django 5.1.15 on 2026-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='progress_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='prospects_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='total_prospects_found',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
